# Generated by Django 3.1.2 on 2020-10-08 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20201008_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poll',
            name='user',
        ),
        migrations.AddField(
            model_name='poll',
            name='poll_title',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
