# Generated by Django 2.2.12 on 2020-10-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_poll_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='polls',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
    ]
