# Generated by Django 2.2.12 on 2020-10-01 15:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20201001_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='polls',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Poll'),
        ),
        migrations.AlterField(
            model_name='poll',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
