# Generated by Django 2.2.12 on 2020-10-01 15:33

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20201001_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='options',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=8),
        ),
        migrations.DeleteModel(
            name='Options',
        ),
    ]
