# Generated by Django 3.1.2 on 2020-10-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_poll_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
