# Generated by Django 2.2.12 on 2020-10-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20201001_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='time_created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
