# Generated by Django 3.1.2 on 2020-10-08 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_poll_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='votes',
            field=models.JSONField(default=dict),
        ),
    ]
