# Generated by Django 2.2.12 on 2020-10-01 21:01

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_poll_time_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='poll',
            name='votes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), null=True, size=8),
        ),
    ]
