# Generated by Django 3.1.2 on 2020-10-08 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_poll_votes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uservoted',
            name='option_chosen',
        ),
        migrations.RemoveField(
            model_name='uservoted',
            name='poll',
        ),
    ]
