# Generated by Django 3.1.2 on 2020-10-08 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20201008_1228'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservoted',
            name='poll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.poll'),
        ),
    ]
